# Generated by Django 4.1.3 on 2022-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('plan_type', models.CharField(max_length=60)),
                ('death_benefits', models.CharField(max_length=60)),
                ('payment_mode', models.CharField(max_length=60)),
                ('sum_assured', models.CharField(max_length=60)),
            ],
        ),
    ]
