# Generated by Django 4.1.3 on 2022-12-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroInsurance',
            new_name='Data',
        ),
    ]
